/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#00685f',
        'on-primary': '#ffffff',
        'primary-container': '#008378',
        'on-primary-container': '#f4fffc',
        'primary-fixed': '#89f5e7',
        'primary-fixed-dim': '#6bd8cb',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#005049',
        'inverse-primary': '#6bd8cb',
        'secondary': '#216963',
        'on-secondary': '#ffffff',
        'secondary-container': '#a8ece5',
        'on-secondary-container': '#266d68',
        'secondary-fixed': '#abefe8',
        'secondary-fixed-dim': '#8fd3cc',
        'on-secondary-fixed': '#00201e',
        'on-secondary-fixed-variant': '#00504b',
        'tertiary': '#545c72',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6c748b',
        'on-tertiary-container': '#fefcff',
        'tertiary-fixed': '#dae2fd',
        'tertiary-fixed-dim': '#bec6e0',
        'on-tertiary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#3f465c',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f9f9f9',
        'on-background': '#1a1c1c',
        'surface': '#f9f9f9',
        'on-surface': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        'on-surface-variant': '#3d4947',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-tint': '#006a61',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        'outline': '#6d7a77',
        'outline-variant': '#bcc9c6',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'xl': '12px',
        '2xl': '16px',
      },
      spacing: {
        'stack-xs': '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'gutter': '24px',
        'margin-desktop': '32px',
        'margin-mobile': '16px',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-stat': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      animation: {
        'spin-slow': 'spin 2s linear infinite',
        'pulse-bar': 'pulse 1.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
